<?php

/**
 * @file
 * Administration navbar for quick access to top level administration items.
 */

/**
 * Implements hook_help().
 */
function navbar_help($path, $arg) {
  switch ($path) {
    case 'admin/help#navbar':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Navbar module displays links to top-level administration menu items and links from other modules at the top of the screen. For more information, see the online handbook entry for <a href="@navbar">Navbar module</a>.', array('@navbar' => 'http://drupal.org/documentation/modules/navbar')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Displaying administrative links') . '</dt>';
      $output .= '<dd>' . t('The Navbar module displays a bar containing top-level administrative links across the top of the screen. Below that, the Navbar module has a <em>drawer</em> section where it displays links provided by other modules, such as the core <a href="@shortcuts-help">Shortcut module</a>. The drawer can be hidden/shown by using the show/hide shortcuts link at the end of the navbar.', array('@shortcuts-help' => url('admin/help/shortcut'))) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function navbar_permission() {
  return array(
    'access navbar' => array(
      'title' => t('Use the administration navbar'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function navbar_theme($existing, $type, $theme, $path) {
  $items['navbar'] = array(
    'render element' => 'navbar',
    'template' => 'navbar',
    'path' => drupal_get_path('module', 'navbar'),
  );
  $items['navbar_toggle'] = array(
    'variables' => array(
      'collapsed' => NULL,
      'attributes' => array(),
    ),
  );
  return $items;
}

/**
 * Implements hook_menu().
 */
function navbar_menu() {
  $items['navbar/toggle'] = array(
    'title' => 'Toggle drawer visibility',
    'type' => MENU_CALLBACK,
    'page callback' => 'navbar_toggle_page',
    'access arguments' => array('access navbar'),
  );
  return $items;
}

/**
 * Page callback: Toggles the visibility of the navbar drawer.
 *
 * @see navbar_menu().
 */
function navbar_toggle_page() {
  global $base_path;
  // Toggle the value in the cookie.
  setcookie('Drupal.navbar.collapsed', !_navbar_is_collapsed(), NULL, $base_path);
  // Redirect the user from where he used the toggle element.
  drupal_goto();
}

/**
 * Formats an element used to toggle the navbar drawer's visibility.
 *
 * @param $variables
 *   An associative array containing:
 *   - collapsed: A boolean value representing the navbar drawer's visibility.
 *   - attributes: An associative array of HTML attributes.
 *
 * @return
 *   An HTML string representing the element for toggling.
 *
 * @ingroup themable
 */
function theme_navbar_toggle($variables) {
  if ($variables['collapsed']) {
    $toggle_text = t('Show shortcuts');
  }
  else {
    $toggle_text = t('Hide shortcuts');
    $variables['attributes']['class'][] = 'toggle-active';
  }
  return l($toggle_text, 'navbar/toggle', array('query' => drupal_get_destination(), 'attributes' => array('title' => $toggle_text) + $variables['attributes']));
}

/**
 * Determines the current state of the navbar drawer's visibility.
 *
 * @return
 *   TRUE when drawer is collapsed, FALSE when it is expanded.
 */
function _navbar_is_collapsed() {
  // PHP converts dots into underscores in cookie names to avoid problems with
  // its parser, so we use a converted cookie name.
  return isset($_COOKIE['Drupal_navbar_collapsed']) ? $_COOKIE['Drupal_navbar_collapsed'] : 0;
}

/**
 * Implements hook_page_build().
 *
 * Add admin navbar to the page_bottom region automatically.
 */
function navbar_page_build(&$page) {
  $page['page_bottom']['navbar'] = array(
    '#pre_render' => array('navbar_pre_render'),
    '#access' => user_access('access navbar'),
    'navbar_drawer' => array(),
  );
}

/**
 * Provides pre_render function for the navbar.
 *
 * Since building the navbar takes some time, it is done just prior to
 * rendering to ensure that it is built only if it will be displayed.
 *
 * @see navbar_page_build().
 */
function navbar_pre_render($navbar) {
  $navbar = array_merge($navbar, navbar_view());
  return $navbar;
}

/**
 * Implements hook_preprocess_HOOK() for html.tpl.php.
 *
 * Add some page classes, so global page theming can adjust to the navbar.
 */
function navbar_preprocess_html(&$vars) {
  if (isset($vars['page']['page_bottom']['navbar']) && user_access('access navbar')) {
    $vars['attributes']['class'][] = 'navbar';
    if (!_navbar_is_collapsed()) {
      $vars['attributes']['class'][] = 'navbar-drawer';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for navbar.tpl.php.
 *
 * Adding the 'overlay-displace-top' class to the navbar pushes the overlay
 * down, so it appears below the navbar.
 */
function navbar_preprocess_navbar(&$variables) {
  $variables['attributes']['class'][] = "overlay-displace-top";
}

/**
 * Implements hook_system_info_alter().
 *
 * Indicate that the 'page_bottom' region (in which the navbar will be displayed)
 * is an overlay supplemental region that should be refreshed whenever its
 * content is updated.
 *
 * This information is provided for any module that might need to use it, not
 * just the core Overlay module.
 */
function navbar_system_info_alter(&$info, $file, $type) {
  if ($type == 'theme') {
    $info['overlay_supplemental_regions'][] = 'page_bottom';
  }
}

/**
 * Builds the admin menu as a structured array ready for drupal_render().
 *
 * @return
 *   Array of links and settings relating to the admin menu.
 */
function navbar_view() {
  global $user;

  $module_path = drupal_get_path('module', 'navbar');
  $build = array(
    '#theme' => 'navbar',
    '#attached'=> array(
      'js' => array(
        $module_path . '/js/navbar.js',
      ),
      'css' => array(
        $module_path . '/css/navbar.css',
      ),
      'library' => array(array('system', 'jquery.cookie')),
    ),
  );

  // Retrieve the admin menu from the database.
  $links = navbar_menu_navigation_links(navbar_get_menu_tree());

  $build['navbar_tray_toggle'] = array(
    '#heading' => array('text' => t('Administrative tray toggle'), 'level' => 'h2', 'class' => 'element-invisible'),
    '#theme' => 'link',
    '#path' => 'admin',
    '#text' => t('Admin tray'),
    '#options' => array(
      'attributes' => array(
        'class' => 'navbar-toggle-tray',
      ),
      'html' => FALSE,
    ),
    
  );

  $build['navbar_filter'] = array(
    '#type' => 'textfield',
    '#value' => t('Search'),
    '#attributes' => array(
      'class' => array('filter')
    ),
  );

  $build['navbar_filter_button'] = array(
    '#theme' => 'link',
    '#path' => '#',
    '#text' => t('Search'),
  );

  $build['navbar_menu'] = array(
    '#theme' => 'links__navbar_menu',
    '#links' => $links,
    '#attributes' => array('id' => 'navbar-menu'),
    '#heading' => array('text' => t('Administrative navbar'), 'level' => 'h2', 'class' => 'element-invisible'),
  );

  // Add logout & user account links or login link.
  if ($user->uid) {
    $links = array(
      'account' => array(
        'title' => t('Hello <strong>@username</strong>', array('@username' => format_username($user))),
        'href' => 'user',
        'html' => TRUE,
        'attributes' => array('title' => t('User account')),
      ),
      'logout' => array(
        'title' => t('Log out'),
        'href' => 'user/logout',
      ),
    );
  }
  else {
     $links = array(
      'login' => array(
        'title' => t('Log in'),
        'href' => 'user',
      ),
    );
  }
  $build['navbar_user'] = array(
    '#theme' => 'links__navbar_user',
    '#links' => $links,
    '#attributes' => array('id' => 'navbar-user'),
  );

  // Add a "home" link.
  $link = array(
    'home' => array(
      'title' => '<span class="home-link">Home</span>',
      'href' => '<front>',
      'html' => TRUE,
      'attributes' => array('title' => t('Home')),
    ),
  );
  $build['navbar_home'] = array(
    '#theme' => 'links',
    '#links' => $link,
    '#attributes' => array('id' => 'navbar-home'),
  );

  // Add an anchor to be able to toggle the visibility of the drawer.
  $build['navbar_toggle'] = array(
    '#theme' => 'navbar_toggle',
    '#collapsed' => _navbar_is_collapsed(),
    '#attributes' => array('class' => array('toggle')),
  );

  // Prepare the drawer links CSS classes.
  $navbar_drawer_classes = array(
    'navbar-drawer',
    'clearfix',
  );
  if (_navbar_is_collapsed()) {
    $navbar_drawer_classes[] = 'collapsed';
  }
  $build['navbar_drawer']['#type'] = 'container';
  $build['navbar_drawer']['#attributes']['class'] = $navbar_drawer_classes;

  return $build;
}

/**
 * Gets only the top level items below the 'admin' path.
 *
 * @return
 *   An array containing a menu tree of top level items below the 'admin' path.
 */
function navbar_get_menu_tree() {
  $tree = array();
  $admin_link = db_query('SELECT * FROM {menu_links} WHERE menu_name = :menu_name AND module = :module AND link_path = :path', array(':menu_name' => 'management', ':module' => 'system', ':path' => 'admin'))->fetchAssoc();
  if ($admin_link) {
    $tree = menu_build_tree('management', array(
      'expanded' => array($admin_link['mlid']),
      'min_depth' => $admin_link['depth'] + 1,
      'max_depth' => $admin_link['depth'] + 1,
    ));
  }

  return $tree;
}

/**
 * Generates an array of links from a menu tree array.
 *
 * Based on menu_navigation_links(). Adds path based IDs and icon placeholders
 * to the links.
 *
 * @return
 *   An array of links as defined above.
 */
function navbar_menu_navigation_links($tree) {
  $links = array();
  foreach ($tree as $item) {
    if (!$item['link']['hidden'] && $item['link']['access']) {
      // Make sure we have a path specific ID in place, so we can attach icons
      // and behaviors to the items.
      $id = str_replace(array('/', '<', '>'), array('-', '', ''), $item['link']['href']);

      $link = $item['link']['localized_options'];
      $link['href'] = $item['link']['href'];
      // Add icon placeholder.
      $link['title'] = '<span class="icon"></span>' . check_plain($item['link']['title']);
      // Add admin link ID.
      $link['attributes'] = array('id' => 'navbar-link-' . $id);
      if (!empty($item['link']['description'])) {
        $link['title'] .= ' <span class="element-invisible">(' . $item['link']['description'] . ')</span>';
        $link['attributes']['title'] = $item['link']['description'];
      }
      $link['html'] = TRUE;

      $class = ' path-' . $id;
      if (navbar_in_active_trail($item['link']['href'])) {
        $class .= ' active-trail';
      }
      $links['menu-' . $item['link']['mlid'] . $class] = $link;
    }
  }
  return $links;
}

/**
 * Checks whether an item is in the active trail.
 *
 * Useful when using a menu generated by menu_tree_all_data() which does
 * not set the 'in_active_trail' flag on items.
 *
 * @return
 *   TRUE when path is in the active trail, FALSE if not.
 *
 * @todo
 *   Look at migrating to a menu system level function.
 */
function navbar_in_active_trail($path) {
  $active_paths = &drupal_static(__FUNCTION__);

  // Gather active paths.
  if (!isset($active_paths)) {
    $active_paths = array();
    $trail = menu_get_active_trail();
    foreach ($trail as $item) {
      if (!empty($item['href'])) {
        $active_paths[] = $item['href'];
      }
    }
  }
  return in_array($path, $active_paths);
}

/**
 * Point the shortcut module to the Navbar instead of the toolbar
 */
/**
 * Implements hook_page_alter().
 */
function navbar_page_alter(&$page) {
  if (module_exists('shortcut')) {
    // If the navbar is available, add a pre-render function to display the
    // current shortcuts in the navbar drawer.
    $page['page_bottom']['navbar']['#pre_render'][] = 'navbar_shortcut_pre_render';
  }
}

/**
 * Pre-render function for adding shortcuts to the toolbar drawer.
 */
function navbar_shortcut_pre_render($navbar) {
  $links = shortcut_renderable_links();
  $links['#attached'] = array('css' => array(drupal_get_path('module', 'shortcut') . '/shortcut.css'));
  $links['#prefix'] = '<div class="toolbar-shortcuts">';
  $links['#suffix'] = '</div>';
  $shortcut_set = shortcut_current_displayed_set();
  $configure_link = NULL;
  if (shortcut_set_edit_access($shortcut_set)) {
    $configure_link = array(
      '#type' => 'link',
      '#title' => t('Edit shortcuts'),
      '#href' => 'admin/config/user-interface/shortcut/' . $shortcut_set->set_name,
      '#options' => array('attributes' => array('id' => 'edit-shortcuts')),
    );
  }

  $drawer = array(
    'shortcuts' => $links,
    'configure' => $configure_link,
  );

  $navbar['navbar_drawer'][] = $drawer;
  return $navbar;
}
